### ISSUE TITLE
Implement platform menu bar for Linux

### ISSUE THREAD

**Issue by adazem009** [scratchcpp/scratchcpp-player#22]

**Comment by Spike1377** [comment]
Is it that menu bar at the top that looks like the on in mac os?

**Comment by adazem009** [comment]
> Is it that menu bar at the top that looks like the on in mac os?

Yes. Some desktop environments such as KDE Plasma or Unity support it and since the Qt Quick MenuBar component doesn't support it, I have to use the MenuBar component from the Qt Labs Platforn module to support it. Even for macOS.

For example, here's a screenshot of the native menu bar in the MuseScore application running in KDE Plasma:

![211918525-7f25a225-1bfb-4b4a-a079-64aa2399d9f3.png](https://github.com/scratchcpp/scratchcpp-player/assets/68537469/47aac10d-0fb2-478d-8a45-99a8db865f8f)

**Comment by Spike1377** [comment]
Ive used musiscore before
