### ISSUE TITLE
Compile instructions on readme

### ISSUE THREAD

**Issue by Spike1377** [scratchcpp/scratchcpp-player#31]
I couldn't figre it out how to compile it, idk what cmake command i use, im not good at compiling things, i can only do it with instruction's pls help

**Comment by adazem009** [comment]
The first step is to install Qt 6.6. On Linux, you can use the `aqt-install` tool for that:
```
pip install -U pip
pip install aqtinstall

aqt install-qt linux desktop 6.6.2 gcc_64 -m qtimageformats --outputdir ~/Qt
```
Qt will be installed in the `~/Qt` directory.

You'll need a few dependencies which can be installed using apt on Debian distros:
```
sudo apt install nlohmann-json3-dev libutfcpp-dev libxcb-cursor0
```

Then, go to the repository directory and create a build directory:
```
mkdir build_files
cd build_files
```
Tell CMake to use the Qt installation you've installed and configure the project:
```
export CMAKE_PREFIX_PATH=~/Qt/6.6.2/gcc_64:$CMAKE_PREFIX_PATH
cmake ..
```
And to build and run the application:
```
cmake --build . -j$(nproc --all)
./src/appscratchcpp-player
```

It is possible to use the Qt Creator IDE for this which is much easier if you configure it correctly.

**Comment by Spike1377** [comment]
Im on Fedora, so the pakage names are diffrent and whatnot, but thanks for pointing me into the right direction.

**Comment by adazem009** [comment]
> Im on Fedora, so the pakage names are diffrent and whatnot, but thanks for pointing me into the right direction.

I'm going to distribute AppImages when I release version 0.1, but I don't know when it's going to be. I'll definitely have an AppImage after this issue is resloved: https://github.com/scratchcpp/scratchcpp-player/issues/7

**Comment by adazem009** [comment]
@Spike1377 I now have automated AppImage building. You can test the initial ScratchCPP Player AppImage if you want. https://github.com/scratchcpp/scratchcpp-player/actions/runs/8110251031/artifacts/1289037092

**Comment by adazem009** [comment]
The complete Linux build instructions are here now: https://github.com/scratchcpp/scratchcpp-player/wiki/Linux-build-instructions

**Comment by Spike1377** [comment]
Nice it looks good.

Now add instructions for other distros, But its fine if you don't ill just use the appimage.

**Comment by adazem009** [comment]
> Nice it looks good. Now add instructions for other distros, But its fine if you don't ill just use the appimage.

Actually, the instructions aren't distro-specific. You just need to know how to install Python and git which I don't think I should cover there.

**Comment by Spike1377** [comment]
Ok thats good.
